### ISSUE TITLE
Can't build the library

### ISSUE THREAD

**Issue by TheExentist151** [Sajidur78/LWAPI#8]
So I've downloaded the library, linked it with my project, included `Sonic2013.h` in my `pch.h` and I'm getting some errors: 
![image](https://github.com/hedge-dev/LWAPI/assets/91889396/3c9cf428-cb65-4663-a931-0dfa2ff4df6c)

I've changed the language standard to C++17, but it didn't help.

**Comment by DeaTh-G** [comment]
As far as I'm aware this issue comes from a change introduced in `Visual Studio 2022 (v143)` platform toolset that @Sajidur78 hasn't fixed yet. Switching to `Visual Studio 2019 (v142)` toolset should allow you to compile.

**Comment by TheExentist151** [comment]
Yes! The issue is fixed now!
